sudo: 'required'

services:
  - 'docker'

before_install:
  - './.travis/main.sh'

script:
  - 'make test'
  - 'make image'

after_success:
  - docker login -u $DOCKER_USERNAME --password-stdin $DOCKER_PASSWORD ;
      make push-image ;
    

notifications:
  email: false

